### ISSUE TITLE
Thanks for this very user tool!

### ISSUE THREAD

**Issue by Venkat-TTapp** [sfreytag/bootstrap-cookie-consent#2]
@ sfreytag

Heartiest thanks for sharing this simple yet very effective and useful tool. I am going to use this for in my iOS & Android Apps.

Is there any possibility of showing the text as marquee as I need to show few line of sentence which takes more space on screen.

Regard,
Venkat

**Comment by sfreytag** [comment]
Thanks for the nice feedback and suggestions. Sorry I never got back to you. My thought at the time was that this is something you should do yourself, rather than something I should build into the widget.

The reason for this is because strictly speaking this widget should not include its own HTML at all. The standard jQuery plugin approach is that it should be just a few JS functions and you should probably build your own HTML and pass in, for example, an ID of a button that can be wired up to a click handler. If it worked like this, then you could add any HTML you wanted,  such as a scrolling marquee.

But I wanted this widget to be something you could just drop in to a project and have it work in isolation. My use-case for this was that I was integrating it with the ModX CMS and having something that could stand alone was very appealing. Hence the HTML is embedded... This HTML is never going to do what everyone who uses this widget would like it to do, so I think the best rule is to keep it as simple as possible, while implementing a few basic Bootstrap classes.

So if you want to add a marquee, you definitely can - just hack it into the HTML included in the JS. Or, build your own HTML to use the functions in this widget, and get rid of the bits that insert the embedded HTML.
